require("alejandro.plugins-setup")

require("alejandro.core.options")
require("alejandro.core.keymaps")
require("alejandro.core.colorscheme")
require("alejandro.plugins.comment")
require("alejandro.plugins.nvim-tree")
require("alejandro.plugins.lualine")
require("alejandro.plugins.nvim-cmp")
require("alejandro.plugins.lsp.mason")
require("alejandro.plugins.lsp.lspsaga")
require("alejandro.plugins.lsp.lspconfig")
require("alejandro.plugins.lsp.null-ls")
require("alejandro.plugins.autopairs")
require("alejandro.plugins.treesitter")
require("alejandro.plugins.gitsigns")
require("alejandro.plugins.toggleterm")
require("alejandro.plugins.bufferline")
